package de.felix0351.models.objects

import de.felix0351.utils.LocalDateTimeSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonObject

import java.time.LocalDateTime

sealed class Meals {



    /**
     *  Used to categorize the meals
     *
     * @property id Unique id of the category, Null if it isn't already in the database
     * @property name Name of the category
     */
    @Serializable
    data class Category(
        val id: Int?,
        val name: String
    )


    /**
     *  Meal Object
     *
     * @property id Unique id of the meal, Null if it isn't already in the database
     * @property name Name of the meal
     * @property description A short description about the meal
     * @property price Price of the meal
     * @property day Day, if the meal is available. Null if the meal is available continuously
     * @property picture Storage adress to the picture of the meal if there is one
     * @property selections Selections to the meal, which will be stored in JSON Format.
     * Templates can be stored in the SelectionGroup Table
     * @property category categoryID(Category Table), can be null if the meal has no category.
     * If the category to the meal will be deleted, then it will be null.
     *
     */

    @Serializable
    data class Meal(
        val id: Int?,
        val name: String,
        val description: String,
        val picture: String?,
        val price: Float,
        val day: String,
        val selections: String?,
        val category: Int?
    )


    /**
     * An Order

     * @property id Unique id of the order, Null if it isn't already in the database
     * @property userID id of the user (User Table), who is ordering
     * @property mealID id of the meal (Meal Table), which was ordered
     * @property time ordering time. Automatically generated by the repository
     *
     */
    @Serializable
    data class Order(
        val id: Int?,
        val userID: Int,
        val mealID: Int,
        @Serializable(with = LocalDateTimeSerializer::class) val time: LocalDateTime
    )


    /**
     * Selection Group template
     *
     * @property id Unique id of the group, Null if it isn't already in the database
     * @property name Name of the group
     * @property elements Data and Elements in the Group (stored in JSON Format)
     *
     */
   @Serializable
    data class SelectionGroup(
        val id: Int?,
        val name: String,
        val elemtents: JsonObject
    )







}
