@startuml
'https://plantuml.com/object-diagram

object User <<Serializable>> {
    + username: String
    + name: String
    + permissionLevel: PermissionLevel
    + credit: Float
    + password: String?
}

enum PermissionLevel {
    Admin
    Worker
    User
}


@enduml
