@startuml
'https://plantuml.com/object-diagram

object Meal<<Serializable>> {

    + id: String
    + category: String?
    + name: String
    + description: String
    + price: Float
    + deposit: String,
    + day: String?
    + selections: List<SelectionGroup>
    + picture: String?

}



@enduml